[package]
name = "chess"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
ratatui = { version = "0.29.0", features = ["unstable-backend-writer"] }
